2022-10-15 09:19:19 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x118d58250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
2022-10-15 09:19:19 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x118d58bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
2022-10-15 09:19:19 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x118d5fd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
2022-10-15 16:07:37 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x13e448880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
2022-10-15 16:07:37 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x13e448f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
2022-10-15 16:07:37 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x13e6b2280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /api/5288891/envelope/
